### ISSUE TITLE
Modify C++ Test Schema Declaration for Function Inputs and Outputs

### ISSUE THREAD

**Issue by threeal** [threeal/leettest#327]
This issue suggests modifying the C++ test schema declaration for function inputs and output information from this:

```yaml
cpp:
  function:
    name: appendStrings
    inputs:
      - type: std::string
        value: str1
      - type: std::string
        value: str2
    output:
      type: std::string
```

to this:

```yaml
cpp:
  function:
    name: appendStrings
    arguments: [str1, str2]
  inputs:
    str1:
      type: std::string
    str2:
      type: std::string
  output:
    type: std::string
```

This change modifies the inputs and output from being related to the arguments and return type of the function to being related to the test case. It means that the `str1` input will have the type `std::string` in C++, and so on.

To simplify things, if `type` is the only property set in the inputs and output, this should be allowed:

```yaml
cpp:
  function:
    name: appendStrings
    arguments: [str1, str2]
  inputs:
    str1: std::string
    str2: std::string
  output: std::string
```

This change may simplify the C++ test schema declaration, streamline test generation, allow checking for incorrect inputs/outputs, and possibly enable easier implementation of C support.
