### ISSUE TITLE
Separate C++ Schema from Raw YAML Schema

### ISSUE THREAD

**Issue by threeal** [threeal/leettest#330]
This issue suggests separating the C++ schema from the raw YAML schema, requiring the C++ test generator functions to be called with the C++ schema instead of the raw YAML schema.

The C++ schema is different from the raw YAML schema. While the raw YAML schema looks like this:
```yaml
{
  cpp: {
    function: {
      name: "sum",
      arguments: ["num1", "num2"],
    },
    inputs: {
      num1: "int",
      num2: "int",
    },
    output: "int",
  },
  cases: [
    {
      name: "example 1",
      inputs: {
        num1: 12,
        num2: 5,
      },
      output: 17,
    },
    {
      name: "example 2",
      inputs: {
        num1: -10,
        num2: 4,
      },
      output: -6,
    },
  ],
}
```

The C++ schema will look like this:
```yaml
[
  {
    name: "example 1",
    function: {
      name: "sum",
      arguments: ["num1", "num2"],
    },
    inputs: {
      num1: {
        type: "int",
        value: 12,
      },
      num2: {
        type: "int",
        value: 5,
      },
    },
    output: {
      type: "int",
      value: 17,
    },
  },
  {
    name: "example 2",
    function: {
      name: "sum",
      arguments: ["num1", "num2"],
    },
    inputs: {
      num1: {
        type: "int",
        value: -10,
      },
      num2: {
        type: "int",
        value: 4,
      },
    },
    output: {
      type: "int",
      value: -6,
    },
  },
]
```

This may make the C++ schema look larger, but it allows for easier generation of C++ test code, enabling C++ test code for a partial test case to be generated and tested without the need to know all test cases.
