### ISSUE TITLE
Modify Function Inputs in Schema to Require a Name

### ISSUE THREAD

**Issue by threeal** [threeal/leettest#71]
This issue suggests modifying the function inputs in schemas to require a `name` property alongside the `type` property. Essentially, this change will modify the following function inputs in the schema:

```yaml
inputs: [int, int]
```

To be like this:

```yaml
inputs:
  - name: nums1
    type: int
  - name: nums2
    type: int
```

This change is proposed to give names to the function inputs. This change is especially required to implement issue #69.
